// @ts-nocheck
/* eslint-disable */
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.19.4
 * source: astra/inflation/v1/genesis.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_2 from "./inflation";
import * as pb_1 from "google-protobuf";
export namespace astra.inflation.v1 {
    export class GenesisState extends pb_1.Message {
        #one_of_decls = [];
        constructor(data?: any[] | {
            params?: Params;
            period?: number;
            epoch_identifier?: string;
            epochs_per_period?: number;
            skipped_epochs?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("params" in data && data.params != undefined) {
                    this.params = data.params;
                }
                if ("period" in data && data.period != undefined) {
                    this.period = data.period;
                }
                if ("epoch_identifier" in data && data.epoch_identifier != undefined) {
                    this.epoch_identifier = data.epoch_identifier;
                }
                if ("epochs_per_period" in data && data.epochs_per_period != undefined) {
                    this.epochs_per_period = data.epochs_per_period;
                }
                if ("skipped_epochs" in data && data.skipped_epochs != undefined) {
                    this.skipped_epochs = data.skipped_epochs;
                }
            }
        }
        get params() {
            return pb_1.Message.getWrapperField(this, Params, 1) as Params;
        }
        set params(value: Params) {
            pb_1.Message.setWrapperField(this, 1, value);
        }
        get period() {
            return pb_1.Message.getField(this, 2) as number;
        }
        set period(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        get epoch_identifier() {
            return pb_1.Message.getField(this, 3) as string;
        }
        set epoch_identifier(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get epochs_per_period() {
            return pb_1.Message.getField(this, 4) as number;
        }
        set epochs_per_period(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get skipped_epochs() {
            return pb_1.Message.getField(this, 5) as number;
        }
        set skipped_epochs(value: number) {
            pb_1.Message.setField(this, 5, value);
        }
        static fromObject(data: {
            params?: ReturnType<typeof Params.prototype.toObject>;
            period?: number;
            epoch_identifier?: string;
            epochs_per_period?: number;
            skipped_epochs?: number;
        }) {
            const message = new GenesisState({});
            if (data.params != null) {
                message.params = Params.fromObject(data.params);
            }
            if (data.period != null) {
                message.period = data.period;
            }
            if (data.epoch_identifier != null) {
                message.epoch_identifier = data.epoch_identifier;
            }
            if (data.epochs_per_period != null) {
                message.epochs_per_period = data.epochs_per_period;
            }
            if (data.skipped_epochs != null) {
                message.skipped_epochs = data.skipped_epochs;
            }
            return message;
        }
        toObject() {
            const data: {
                params?: ReturnType<typeof Params.prototype.toObject>;
                period?: number;
                epoch_identifier?: string;
                epochs_per_period?: number;
                skipped_epochs?: number;
            } = {};
            if (this.params != null) {
                data.params = this.params.toObject();
            }
            if (this.period != null) {
                data.period = this.period;
            }
            if (this.epoch_identifier != null) {
                data.epoch_identifier = this.epoch_identifier;
            }
            if (this.epochs_per_period != null) {
                data.epochs_per_period = this.epochs_per_period;
            }
            if (this.skipped_epochs != null) {
                data.skipped_epochs = this.skipped_epochs;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.params !== undefined)
                writer.writeMessage(1, this.params, () => this.params.serialize(writer));
            if (this.period !== undefined)
                writer.writeUint64(2, this.period);
            if (typeof this.epoch_identifier === "string" && this.epoch_identifier.length)
                writer.writeString(3, this.epoch_identifier);
            if (this.epochs_per_period !== undefined)
                writer.writeInt64(4, this.epochs_per_period);
            if (this.skipped_epochs !== undefined)
                writer.writeUint64(5, this.skipped_epochs);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GenesisState {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GenesisState();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.params, () => message.params = Params.deserialize(reader));
                        break;
                    case 2:
                        message.period = reader.readUint64();
                        break;
                    case 3:
                        message.epoch_identifier = reader.readString();
                        break;
                    case 4:
                        message.epochs_per_period = reader.readInt64();
                        break;
                    case 5:
                        message.skipped_epochs = reader.readUint64();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): GenesisState {
            return GenesisState.deserialize(bytes);
        }
    }
    export class Params extends pb_1.Message {
        #one_of_decls = [];
        constructor(data?: any[] | {
            mint_denom?: string;
            inflation_parameters?: dependency_2.astra.inflation.v1.InflationParameters;
            enable_inflation?: boolean;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("mint_denom" in data && data.mint_denom != undefined) {
                    this.mint_denom = data.mint_denom;
                }
                if ("inflation_parameters" in data && data.inflation_parameters != undefined) {
                    this.inflation_parameters = data.inflation_parameters;
                }
                if ("enable_inflation" in data && data.enable_inflation != undefined) {
                    this.enable_inflation = data.enable_inflation;
                }
            }
        }
        get mint_denom() {
            return pb_1.Message.getField(this, 1) as string;
        }
        set mint_denom(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get inflation_parameters() {
            return pb_1.Message.getWrapperField(this, dependency_2.astra.inflation.v1.InflationParameters, 2) as dependency_2.astra.inflation.v1.InflationParameters;
        }
        set inflation_parameters(value: dependency_2.astra.inflation.v1.InflationParameters) {
            pb_1.Message.setWrapperField(this, 2, value);
        }
        get enable_inflation() {
            return pb_1.Message.getField(this, 3) as boolean;
        }
        set enable_inflation(value: boolean) {
            pb_1.Message.setField(this, 3, value);
        }
        static fromObject(data: {
            mint_denom?: string;
            inflation_parameters?: ReturnType<typeof dependency_2.astra.inflation.v1.InflationParameters.prototype.toObject>;
            enable_inflation?: boolean;
        }) {
            const message = new Params({});
            if (data.mint_denom != null) {
                message.mint_denom = data.mint_denom;
            }
            if (data.inflation_parameters != null) {
                message.inflation_parameters = dependency_2.astra.inflation.v1.InflationParameters.fromObject(data.inflation_parameters);
            }
            if (data.enable_inflation != null) {
                message.enable_inflation = data.enable_inflation;
            }
            return message;
        }
        toObject() {
            const data: {
                mint_denom?: string;
                inflation_parameters?: ReturnType<typeof dependency_2.astra.inflation.v1.InflationParameters.prototype.toObject>;
                enable_inflation?: boolean;
            } = {};
            if (this.mint_denom != null) {
                data.mint_denom = this.mint_denom;
            }
            if (this.inflation_parameters != null) {
                data.inflation_parameters = this.inflation_parameters.toObject();
            }
            if (this.enable_inflation != null) {
                data.enable_inflation = this.enable_inflation;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (typeof this.mint_denom === "string" && this.mint_denom.length)
                writer.writeString(1, this.mint_denom);
            if (this.inflation_parameters !== undefined)
                writer.writeMessage(2, this.inflation_parameters, () => this.inflation_parameters.serialize(writer));
            if (this.enable_inflation !== undefined)
                writer.writeBool(3, this.enable_inflation);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Params {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Params();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.mint_denom = reader.readString();
                        break;
                    case 2:
                        reader.readMessage(message.inflation_parameters, () => message.inflation_parameters = dependency_2.astra.inflation.v1.InflationParameters.deserialize(reader));
                        break;
                    case 3:
                        message.enable_inflation = reader.readBool();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Params {
            return Params.deserialize(bytes);
        }
    }
}
